### ISSUE TITLE
Not an issue, just a quote

### ISSUE THREAD

**Issue by RetrogradeDev** [codingMASTER398/noreplit.com#18]
"First, replit was a place for new developers to built anything they want. Now, it's a place for dangerous AI and people that can effort it."

**Comment by codingMASTER398** [comment]
Make a pull request, please

**Comment by RixInGithub** [comment]
I agree to everything the site has to tell. This is just, a yet another way of protesting against Replit, and literally everyone today could make a way better Replit with less money, more uptime, and practically anything we'd like. However, the angry angry CEO says otherwise. I blame Replit for not being able to communicate properly with the community. I was going to make the same rant, though inside of Replit, but I just thought that some random person's gonna say "BAN THE HATERS" and would've banned me for life. I honestly don't mind getting banned now, compared to 2 years ago, I actually think it'd be pretty funny.

Nevertheless, I'm sorry for this rant, you can easily ignore this by now, or, add something from my rant as a quote (would be thankful). Will drop a PR for a static hosting service that I'd think everyone should know.
